alias a='cat'
alias c='cd && l'
alias e='echo'
alias f='find . -iname "*$1*"'
alias g='grep -E'
h() ( "$1" --help | l; )
alias l='ls -A -1 --color=auto --group-directories-first'
alias m='man'
alias o='xdg-open'
alias s='less'
alias x='xsel -b'
alias v='vim'
