= Essays
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:toc: macro
:toclevels: 6
:toc-title:

Original writings and quirky thoughts by me. People might like reading this once I become world famous for something.

toc::[]

== TODO move to adoc

. Real events
.. link:inspire-teenagers-for-technology.md[Inspire teenagers for technology]
.. link:day-in-pompeii.md[A day in Pompeii]
.. link:falun-gong-persecution.md[Falun Gong persecution]
... link:falun-gong-persecution-pt.md[Falun Gong persecution pt]
... link:falun-gong-persecution-zh.md[Falun Gong persecution zh]
... link:open-sourcer-meets-b2b.md[Open Sourcer meets B2B]
. link:people-with-my-family-name.md[People with my family name]
. link:replace-mailing-lists-with-bug-trackers.md[Replace mailing lists with bug trackers]
. link:questions-for-my-future-self.md[Questions for my future self]
. Learning
.. link:how-to-learn-anything.md[How to learn anything]
.. link:how-to-become-a-good-programmer.md[How to become a good programmer]
.. link:tech-motivation-k12.md[Tech motivation K12]
. Poetic
.. link:four-treasures-of-the-hacker.md[The Four Treasures of the Hacker]
.. link:people-know-the-best.md[People know the best]
.. link:quotes.md[Quotes]
. Philosophy
.. link:thoughts.md[Thoughts]
.. link:my-personality.md[My personality]

== Programming

=== Programming language choice

How I feel about various programming languages.

First, I feel that there is only space for two languages at most in the world: the compiled one, and the interpreted one.

For now, when I have the choice, I'll go for:

* Python as the interpreted one
* C++ for compiled

I also do some Bash when I'm lazy. But if the project goes on, I sooner or later regret that choice :-)

Those two are not by any means perfect from a language design point of view, and there are likely already better alternatives. I only choose them due to a pragmatic tradeoff between ecosystem and familiarity.

How I view other languages:

* C cool, but cannot make a large codebase DRY without insanity
* Ruby: the exact same as Python, and only strong in one domain: web, while Python rules everything else, and is not bad on web either. So just kill Ruby, please.
* JavaScript: I'm totally fine if NodeJS destroys Python and becomes the ONE scripting language to rule them all since Python and JavaScript are almost equally crappy.
+
I just don't use it much because of ecosystem / unfamiliarity.
* Java: good language, but I don't like the enterprisey ecosystem, and how closed Oracle has made the development process, and API patenting madness on Android.
* Haskell: I tried to learn some functional stuff, but too hard. Sounds really cool though.
* Rust: sounds cool, I would gladly replace C and C++ with it if the ecosystem ramps up.
* Go: likely a good replacement for Python. If the ecosystem gets there, I'll gladly use it more.
* Swift: I'm not an Apple person.
* Tcl, Perl: I'm not old enough for that, Python killed them before I awoke to programming. And I'm glad, Python feels less insane from my little exposure.

Last update: 2019-03

=== Moving from markdown to asciidoc

Coming from markdown, I've fallen in love with AsciiDoc for anything that has considerable size, around 2018-02 https://github.com/cirosantilli/linux-kernel-module-cheat/commit/254c8bf42e57bb54a715f151ec31b4c87a119faa

AsciiDoc It takes markdown, and adds just enough to write serious books, while still reducing some markdown annoyances.

Oh, and after I was converted, I found out that Buildroot, which is a project I love, also uses it: link:https://buildroot.org/downloads/manual/manual.html[]. How I found it out: "Hey, their docs are perfect, they can't be using AsciiDoc, can they? (greps source) Oh, AsciiDoc!!!".

Reasons:

* Table of Contents. Table of Contents. Table of Contents. One page. Ctrl+F finds everything. `sed` refactors everything. No GitHub Pages faff: page formatting effort, broken builds on forced dependency updates, non-immediate updates. Focused PageRank. ToC. ToC. ToC. https://github.com/isaacs/github/issues/215
* you can link to headers, gives headers custom IDs independent of text, and with `asciidoctor -v` get a warning for broken links
* include directives, if your document gets really humongous. TODO: header resolution not decent across documents yet: 
* you can do everything without indentation, which is hard to type on browser boxes. Nested lists and code blocks notably. GitHub even added the triple backticks block code extension syntax because of that!
* `link::mycode.c[]` instead of `[mycode.c](mycode.c)`, less duplication

Like any love, it is not perfect:

* escaping stuff is painful. Backslash doesn't work...
** `C++`
**  inline code: https://github.com/asciidoctor/asciidoctor/issues/2582
* GitHub uses it's own default header ID calculation mechanism, which can get out of sync with your local version: https://github.com/asciidoctor/asciidoctor/issues/3093

but the thorns add to the thrill.

Wishlist:

* https://github.com/asciidoctor/asciidoctor/issues/3148 Allows setting ID prefix blocks under any header with automatic resolution from inside the header
* https://github.com/asciidoctor/asciidoctor/issues/3147 Warn on automatically generated ID duplicates

Ciro s2 adoc 2018.

Last update: 2019-03

== Stack Overflow

=== Stack Overflow answer style guide

link:stack-overflow-answer-style-guide.md[]

=== Stack Overflow suspension for vote fraud script 2019-03-20

After I got a lot of attention on Hacker News https://news.ycombinator.com/item?id=19428700 my Stack Overflow account was suspended for 3 days http://web.archive.org/web/20190320163458/https://stackoverflow.com/users/895245/ciro-santilli-新疆改造中心-六四事件-法轮功 and I received a magic notification that led to a private message:

____
Hello,

I'm writing in reference to your Stack Overflow account:

I don't understand why you are actively promoting and assisting people to commit fraud on the site.

I've removed this from your profile https://github.com/cirosantilli/stack-overflow-vote-fraud-script and do not expect you to post it around the site.

I'm suspending you to gain your attention on this matter.

We have temporarily suspended your account; you may return after 3 days.

Regards,

Stack Overflow Moderation Team

To: Aaron Hall ♦;Andy ♦;Baum mit Augen ♦;Bhargav Rao ♦;Bohemian ♦;BoltClock ♦;Brad Larson ♦;ChrisF ♦;Cody Gray ♦;deceze ♦;Ed Cottrell ♦;Flexo ♦;George Stocker ♦;Jean-François Fabre ♦;Jon Clements ♦;josliber ♦;Madara Uchiha ♦;Martijn Pieters ♦;meagar ♦;Michael Myers ♦;Rob ♦;Robert Harvey ♦;Ry- ♦;Samuel Liew ♦;Undo ♦;Yvette Colomb ♦
____

My reply:

____

Hi mods,

. https://en.wikipedia.org/wiki/Security_through_obscurity
+
https://en.wikipedia.org/wiki/Kerckhoffs%27s_principle
+
https://stackoverflow.com/questions/533965/why-is-security-through-obscurity-a-bad-idea
+
Security by obscurity does not work. If that is all Stack Overflow relies on, and that is what it looks like, then it is guaranteed to be flawed and already been attacked. 
+
That is one of the reasons that my website will eventually beat Stack Overflow: https://github.com/cirosantilli/write-free-science-books-to-get-famous-website/tree/d77b18d2e7acb3558615797c36195f60dfd26306#pagerank-with-tags
. If you had messaged me and told me "take down or suspend" I would have done it immediately because I understand the meaning of political power.
+
That would have been the better course of action for everyone: I get no block, and you get no bad publicity as I shout Kerckhoff's principle on Twitter.
+
But maybe it is a good thing that people learn more about that.
. Is there an existing public discussion saying that you cannot advertise vote fraud tools on this website?
+
If not, can you please create that meta thread as a reference for future users, and perhaps let the community decide by itself?
+
In particular, will you still suspend me if I don't take down the GitHub repo?
+
Because if not, does it make any sense to prevent it from being mentioned in Stack Overflow? Any good GitHub repo just gets enough Google pagerank that it won't matter.
+
And if yes, nothing prevents me from re-uploading on an anonymous account.
____

https://twitter.com/cirosantilli/status/1108413211840339970

Reply and unsuspend quickly followed, with link still removed:

____
I suspended you to get your attention. Your attitude about going to Twitter about it does not bode well with me.

Feel free to have whatever you want in your GitHub repo. Just don't advertise tools to make it easier for people to circumvent the rules. As easy or as hard as it may be to circumvent them, you're handing it to people who may not be capable of doing so. It doesn't help.

Don't make threats to upload on an anonymous account. Accounts created to circumvent previous warnings are not welcomed on the site.

We don't need a meta thread to discuss whether it's ok to post voting fraud links in your profile and we definitely don't need to give it anymore publicity.

I'll unsuspend you, now we've had this discussion.

Regards,

Stack Overflow Moderation Team
____

A meta thread was later created by Yvette, to which I answered with the correct unpopular answer that will be downvoted to oblivion: https://meta.stackoverflow.com/questions/381577/is-it-ok-to-have-links-on-how-to-create-sock-puppets-and-gain-rep-fraudulently-i/381635#381635
