= Essays
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:toc: macro
:toclevels: 6
:toc-title:

Original writings and quirky thoughts by me. People might like reading this once I become world famous for something. The best of this content has / will be moved to https://cirosantilli.com

toc::[]

== TODO move to adoc

. Real events
.. link:inspire-teenagers-for-technology.md[Inspire teenagers for technology]
.. link:day-in-pompeii.md[A day in Pompeii]
.. link:open-sourcer-meets-b2b.md[Open Sourcer meets B2B]
. Learning
.. link:how-to-learn-anything.md[How to learn anything]
.. link:how-to-become-a-good-programmer.md[How to become a good programmer]
.. link:tech-motivation-k12.md[Tech motivation K12]
. Poetic
.. link:four-treasures-of-the-hacker.md[The Four Treasures of the Hacker]
.. link:people-know-the-best.md[People know the best]
. Philosophy
.. link:thoughts.md[Thoughts]
.. link:my-personality.md[My personality]

== Programming

=== Moving from markdown to asciidoc

Coming from markdown, I've fallen in love with AsciiDoc for anything that has considerable size, around 2018-02 https://github.com/cirosantilli/linux-kernel-module-cheat/commit/254c8bf42e57bb54a715f151ec31b4c87a119faa

Oh, and after I was converted, I found out that Buildroot, which is a project I love, also uses it: link:https://buildroot.org/downloads/manual/manual.html[]. How I found it out: "Hey, their docs are perfect, they can't be using AsciiDoc, can they? (greps source) Oh, AsciiDoc!!!".

Rationale: http://www.cirosantilli.com/markdown-style-guide/#use-asciidoc

Ciro s2 adoc 2018.

Last update: 2019-03

== Stack Overflow

=== Stack Overflow answer style guide

link:stack-overflow-answer-style-guide.md[]
